/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primeiravaliacao;

/**
 *
 * @author mateus
 */
public class mainframe extends javax.swing.JFrame {

    primeiraimplementacao p = new primeiraimplementacao();
    segundaimplementacao s = new segundaimplementacao();
    terceiraimplementacao t = new terceiraimplementacao();

    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
        setSize(480,321);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        limpa1 = new javax.swing.JButton();
        limpa3 = new javax.swing.JButton();
        limpa5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        result1 = new javax.swing.JLabel();
        result2 = new javax.swing.JLabel();
        result3 = new javax.swing.JLabel();
        limparesult1 = new javax.swing.JButton();
        limparesult2 = new javax.swing.JButton();
        limparesult3 = new javax.swing.JButton();
        limpa2 = new javax.swing.JButton();
        limpa4 = new javax.swing.JButton();
        limpa6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 75));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 397, 0, 0);

        txt1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt1);
        txt1.setBounds(10, 160, 70, 24);

        txt3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txt3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txt3);
        txt3.setBounds(10, 200, 70, 24);

        txt5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txt5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txt5);
        txt5.setBounds(10, 240, 70, 24);

        limpa1.setBackground(new java.awt.Color(255, 255, 255));
        limpa1.setFont(new java.awt.Font("Candara", 1, 10)); // NOI18N
        limpa1.setText("<-");
        limpa1.setAlignmentY(0.0F);
        limpa1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        limpa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpa1ActionPerformed(evt);
            }
        });
        getContentPane().add(limpa1);
        limpa1.setBounds(80, 160, 30, 20);

        limpa3.setBackground(new java.awt.Color(255, 255, 255));
        limpa3.setFont(new java.awt.Font("Candara", 1, 10)); // NOI18N
        limpa3.setText("<-");
        limpa3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        limpa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpa3ActionPerformed(evt);
            }
        });
        getContentPane().add(limpa3);
        limpa3.setBounds(80, 200, 30, 20);

        limpa5.setBackground(new java.awt.Color(255, 255, 255));
        limpa5.setFont(new java.awt.Font("Candara", 1, 10)); // NOI18N
        limpa5.setText("<-");
        limpa5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        limpa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpa5ActionPerformed(evt);
            }
        });
        getContentPane().add(limpa5);
        limpa5.setBounds(80, 240, 30, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("+");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 160, 20, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 200, 20, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("*");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 240, 10, 20);

        txt2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txt2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt2);
        txt2.setBounds(140, 160, 70, 24);

        txt4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txt4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txt4);
        txt4.setBounds(140, 200, 70, 24);

        txt6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txt6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txt6);
        txt6.setBounds(140, 240, 70, 24);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton1.setText("=");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 160, 41, 23);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton2.setText("=");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 200, 39, 27);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton3.setText("=");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 240, 40, 27);

        result1.setBackground(new java.awt.Color(255, 255, 255));
        result1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        result1.setForeground(new java.awt.Color(255, 255, 255));
        result1.setText("Resultado");
        result1.setToolTipText("");
        getContentPane().add(result1);
        result1.setBounds(320, 160, 70, 21);

        result2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        result2.setForeground(new java.awt.Color(255, 255, 255));
        result2.setText("Resultado");
        getContentPane().add(result2);
        result2.setBounds(320, 200, 70, 21);

        result3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        result3.setForeground(new java.awt.Color(255, 255, 255));
        result3.setText("Resultado");
        getContentPane().add(result3);
        result3.setBounds(320, 240, 70, 21);

        limparesult1.setBackground(new java.awt.Color(255, 255, 255));
        limparesult1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        limparesult1.setText("Limpar");
        limparesult1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparesult1ActionPerformed(evt);
            }
        });
        getContentPane().add(limparesult1);
        limparesult1.setBounds(400, 160, 70, 27);

        limparesult2.setBackground(new java.awt.Color(255, 255, 255));
        limparesult2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        limparesult2.setText("Limpar");
        limparesult2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparesult2ActionPerformed(evt);
            }
        });
        getContentPane().add(limparesult2);
        limparesult2.setBounds(400, 200, 70, 27);

        limparesult3.setBackground(new java.awt.Color(255, 255, 255));
        limparesult3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        limparesult3.setText("Limpar");
        limparesult3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparesult3ActionPerformed(evt);
            }
        });
        getContentPane().add(limparesult3);
        limparesult3.setBounds(400, 240, 70, 27);

        limpa2.setBackground(new java.awt.Color(255, 255, 255));
        limpa2.setFont(new java.awt.Font("Candara", 1, 10)); // NOI18N
        limpa2.setText("<-");
        limpa2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        limpa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpa2ActionPerformed(evt);
            }
        });
        getContentPane().add(limpa2);
        limpa2.setBounds(210, 160, 30, 20);

        limpa4.setBackground(new java.awt.Color(255, 255, 255));
        limpa4.setFont(new java.awt.Font("Candara", 1, 10)); // NOI18N
        limpa4.setText("<-");
        limpa4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        limpa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpa4ActionPerformed(evt);
            }
        });
        getContentPane().add(limpa4);
        limpa4.setBounds(210, 200, 30, 20);

        limpa6.setBackground(new java.awt.Color(255, 255, 255));
        limpa6.setFont(new java.awt.Font("Candara", 1, 10)); // NOI18N
        limpa6.setText("<-");
        limpa6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        limpa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpa6ActionPerformed(evt);
            }
        });
        getContentPane().add(limpa6);
        limpa6.setBounds(210, 240, 30, 20);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/background.jpg"))); // NOI18N
        jLabel6.setToolTipText("");
        jLabel6.setMaximumSize(new java.awt.Dimension(580, 421));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 480, 320);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 210, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void limpa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpa1ActionPerformed
        // TODO add your handling code here:
        txt1.setText(Integer.toString(p.getlimpa1()));
    }//GEN-LAST:event_limpa1ActionPerformed

    private void limpa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpa3ActionPerformed
        // TODO add your handling code here:
        txt3.setText(Integer.toString(s.getlimpa1()));
    }//GEN-LAST:event_limpa3ActionPerformed

    private void limpa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpa5ActionPerformed
        // TODO add your handling code here:
        txt5.setText(Integer.toString(t.getlimpa1()));
    }//GEN-LAST:event_limpa5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txt1.getText());
        double n2 = Double.parseDouble(txt2.getText());
        result1.setText(Double.toString(p.calcular(n1, n2)));
        p.entrarprograma();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txt3.getText());
        double n2 = Double.parseDouble(txt4.getText());
        result2.setText(Double.toString(s.calcular(n1, n2)));
        s.entrarprograma();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txt5.getText());
        double n2 = Double.parseDouble(txt6.getText());
        result3.setText(Double.toString(t.calcular(n1, n2)));
        t.entrarprograma();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void limparesult1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparesult1ActionPerformed
        // TODO add your handling code here:
        result1.setText(Integer.toString(p.getlimpa()));
        p.limpa();
    }//GEN-LAST:event_limparesult1ActionPerformed

    private void limparesult2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparesult2ActionPerformed
        // TODO add your handling code here:
        result2.setText(Integer.toString(s.getlimpa()));
        s.limpa();
    }//GEN-LAST:event_limparesult2ActionPerformed

    private void limparesult3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparesult3ActionPerformed
        // TODO add your handling code here:
        result3.setText(Integer.toString(t.getlimpa()));
        t.limpa();
    }//GEN-LAST:event_limparesult3ActionPerformed

    private void limpa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpa2ActionPerformed
        // TODO add your handling code here:
        txt2.setText(Integer.toString(p.getlimpa2()));
    }//GEN-LAST:event_limpa2ActionPerformed

    private void limpa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpa4ActionPerformed
        // TODO add your handling code here:
        txt4.setText(Integer.toString(s.getlimpa2()));
    }//GEN-LAST:event_limpa4ActionPerformed

    private void limpa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpa6ActionPerformed
        // TODO add your handling code here:
        txt6.setText(Integer.toString(t.getlimpa2()));
    }//GEN-LAST:event_limpa6ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainframe().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton limpa1;
    private javax.swing.JButton limpa2;
    private javax.swing.JButton limpa3;
    private javax.swing.JButton limpa4;
    private javax.swing.JButton limpa5;
    private javax.swing.JButton limpa6;
    private javax.swing.JButton limparesult1;
    private javax.swing.JButton limparesult2;
    private javax.swing.JButton limparesult3;
    private javax.swing.JLabel result1;
    private javax.swing.JLabel result2;
    private javax.swing.JLabel result3;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    // End of variables declaration//GEN-END:variables
}
